services:
  postgres:
    image: postgres:16-alpine
    container_name: nua-salud-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: nua
      POSTGRES_PASSWORD: nua_secret
      POSTGRES_DB: nua_salud
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

volumes:
  pgdata:
