// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: filters.sql

package operationalsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listClinics = `-- name: ListClinics :many
SELECT id, name FROM clinics WHERE active = true ORDER BY name
`

type ListClinicsRow struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// Clínicas activas para el selector de filtros
func (q *Queries) ListClinics(ctx context.Context) ([]ListClinicsRow, error) {
	rows, err := q.db.Query(ctx, listClinics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClinicsRow
	for rows.Next() {
		var i ListClinicsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDoctors = `-- name: ListDoctors :many
SELECT d.id, d.name, d.specialty, d.clinic_id
FROM doctors d
WHERE d.active = true
  AND ($1::varchar IS NULL OR d.clinic_id = $1)
ORDER BY d.name
`

type ListDoctorsRow struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Specialty Specialty `json:"specialty"`
	ClinicID  string    `json:"clinic_id"`
}

// Doctoras activas, opcionalmente filtradas por clínica
func (q *Queries) ListDoctors(ctx context.Context, clinicID pgtype.Text) ([]ListDoctorsRow, error) {
	rows, err := q.db.Query(ctx, listDoctors, clinicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDoctorsRow
	for rows.Next() {
		var i ListDoctorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Specialty,
			&i.ClinicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpecialties = `-- name: ListSpecialties :many
SELECT DISTINCT specialty FROM services WHERE active = true ORDER BY specialty
`

// Especialidades disponibles en servicios
func (q *Queries) ListSpecialties(ctx context.Context) ([]Specialty, error) {
	rows, err := q.db.Query(ctx, listSpecialties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Specialty
	for rows.Next() {
		var specialty Specialty
		if err := rows.Scan(&specialty); err != nil {
			return nil, err
		}
		items = append(items, specialty)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
