// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: m1_appointments.sql

package operationalsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAppointmentsByPeriod = `-- name: GetAppointmentsByPeriod :many
SELECT
    CASE
        WHEN $1::text = 'day'   THEN to_char(a.date, 'YYYY-MM-DD')
        WHEN $1::text = 'week'  THEN to_char(date_trunc('week', a.date), 'YYYY-MM-DD')
        WHEN $1::text = 'month' THEN to_char(a.date, 'YYYY-MM')
    END AS period,
    COUNT(*) FILTER (WHERE a.status = 'completada') AS completed,
    COUNT(*) FILTER (WHERE a.status = 'cancelada')  AS cancelled,
    COUNT(*) FILTER (WHERE a.status = 'no_show')    AS no_show,
    COUNT(*) AS total
FROM appointments a
JOIN doctors d ON d.id = a.doctor_id
WHERE a.date BETWEEN $2::date AND $3::date
  AND ($4::varchar IS NULL OR a.clinic_id = ANY(string_to_array($4::varchar, ',')))
  AND ($5::varchar IS NULL OR a.doctor_id = $5)
  AND ($6::specialty IS NULL OR d.specialty = $6)
GROUP BY period
ORDER BY period
`

type GetAppointmentsByPeriodParams struct {
	GroupBy   string        `json:"group_by"`
	DateFrom  pgtype.Date   `json:"date_from"`
	DateTo    pgtype.Date   `json:"date_to"`
	ClinicID  pgtype.Text   `json:"clinic_id"`
	DoctorID  pgtype.Text   `json:"doctor_id"`
	Specialty NullSpecialty `json:"specialty"`
}

type GetAppointmentsByPeriodRow struct {
	Period    interface{} `json:"period"`
	Completed int64       `json:"completed"`
	Cancelled int64       `json:"cancelled"`
	NoShow    int64       `json:"no_show"`
	Total     int64       `json:"total"`
}

// M1: Citas agrupadas por período con desglose por estado.
// Agrupa por día, semana o mes según el parámetro @group_by.
func (q *Queries) GetAppointmentsByPeriod(ctx context.Context, arg GetAppointmentsByPeriodParams) ([]GetAppointmentsByPeriodRow, error) {
	rows, err := q.db.Query(ctx, getAppointmentsByPeriod,
		arg.GroupBy,
		arg.DateFrom,
		arg.DateTo,
		arg.ClinicID,
		arg.DoctorID,
		arg.Specialty,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAppointmentsByPeriodRow
	for rows.Next() {
		var i GetAppointmentsByPeriodRow
		if err := rows.Scan(
			&i.Period,
			&i.Completed,
			&i.Cancelled,
			&i.NoShow,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppointmentsSummary = `-- name: GetAppointmentsSummary :one
SELECT
    COUNT(*) AS total,
    COUNT(*) FILTER (WHERE a.status = 'completada') AS completed,
    COUNT(*) FILTER (WHERE a.status = 'cancelada')  AS cancelled,
    COUNT(*) FILTER (WHERE a.status = 'no_show')    AS no_show
FROM appointments a
JOIN doctors d ON d.id = a.doctor_id
WHERE a.date BETWEEN $1::date AND $2::date
  AND ($3::varchar IS NULL OR a.clinic_id = ANY(string_to_array($3::varchar, ',')))
  AND ($4::varchar IS NULL OR a.doctor_id = $4)
  AND ($5::specialty IS NULL OR d.specialty = $5)
`

type GetAppointmentsSummaryParams struct {
	DateFrom  pgtype.Date   `json:"date_from"`
	DateTo    pgtype.Date   `json:"date_to"`
	ClinicID  pgtype.Text   `json:"clinic_id"`
	DoctorID  pgtype.Text   `json:"doctor_id"`
	Specialty NullSpecialty `json:"specialty"`
}

type GetAppointmentsSummaryRow struct {
	Total     int64 `json:"total"`
	Completed int64 `json:"completed"`
	Cancelled int64 `json:"cancelled"`
	NoShow    int64 `json:"no_show"`
}

// M1: Totales de KPI para el período seleccionado
func (q *Queries) GetAppointmentsSummary(ctx context.Context, arg GetAppointmentsSummaryParams) (GetAppointmentsSummaryRow, error) {
	row := q.db.QueryRow(ctx, getAppointmentsSummary,
		arg.DateFrom,
		arg.DateTo,
		arg.ClinicID,
		arg.DoctorID,
		arg.Specialty,
	)
	var i GetAppointmentsSummaryRow
	err := row.Scan(
		&i.Total,
		&i.Completed,
		&i.Cancelled,
		&i.NoShow,
	)
	return i, err
}
