// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: m2_occupancy.sql

package operationalsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOccupancyByClinic = `-- name: GetOccupancyByClinic :many
WITH clinic_doctors AS (
    SELECT clinic_id, COUNT(*) AS doctor_count
    FROM doctors
    WHERE active = true
    GROUP BY clinic_id
),
booked AS (
    SELECT a.clinic_id, COUNT(*) AS booked_slots
    FROM appointments a
    WHERE a.date BETWEEN $3::date AND $4::date
    GROUP BY a.clinic_id
)
SELECT
    c.id AS clinic_id,
    c.name AS clinic_name,
    (c.slots_per_day * $1::integer * COALESCE(cd.doctor_count, 0))::bigint AS available_slots,
    COALESCE(b.booked_slots, 0)::bigint AS booked_slots,
    CASE
        WHEN (c.slots_per_day * $1::integer * COALESCE(cd.doctor_count, 0)) = 0 THEN 0::numeric
        ELSE ROUND(COALESCE(b.booked_slots, 0)::numeric / (c.slots_per_day * $1::integer * COALESCE(cd.doctor_count, 0)) * 100, 1)
    END AS occupancy_rate
FROM clinics c
LEFT JOIN clinic_doctors cd ON cd.clinic_id = c.id
LEFT JOIN booked b ON b.clinic_id = c.id
WHERE c.active = true
  AND ($2::varchar IS NULL OR c.id = $2)
ORDER BY occupancy_rate DESC
`

type GetOccupancyByClinicParams struct {
	TotalDays int32       `json:"total_days"`
	ClinicID  pgtype.Text `json:"clinic_id"`
	DateFrom  pgtype.Date `json:"date_from"`
	DateTo    pgtype.Date `json:"date_to"`
}

type GetOccupancyByClinicRow struct {
	ClinicID       string      `json:"clinic_id"`
	ClinicName     string      `json:"clinic_name"`
	AvailableSlots int64       `json:"available_slots"`
	BookedSlots    int64       `json:"booked_slots"`
	OccupancyRate  interface{} `json:"occupancy_rate"`
}

// M2: Tasa de ocupación por clínica.
// Recibe días_en_rango precalculado desde Go para evitar aritmética de fechas en sqlc.
func (q *Queries) GetOccupancyByClinic(ctx context.Context, arg GetOccupancyByClinicParams) ([]GetOccupancyByClinicRow, error) {
	rows, err := q.db.Query(ctx, getOccupancyByClinic,
		arg.TotalDays,
		arg.ClinicID,
		arg.DateFrom,
		arg.DateTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOccupancyByClinicRow
	for rows.Next() {
		var i GetOccupancyByClinicRow
		if err := rows.Scan(
			&i.ClinicID,
			&i.ClinicName,
			&i.AvailableSlots,
			&i.BookedSlots,
			&i.OccupancyRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
