// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: m3_patients.sql

package operationalsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getNewVsReturning = `-- name: GetNewVsReturning :one
WITH first_visit AS (
    SELECT patient_id, MIN(date) AS first_date
    FROM appointments
    WHERE status = 'completada'
    GROUP BY patient_id
),
period_patients AS (
    SELECT DISTINCT a.patient_id, fv.first_date
    FROM appointments a
    JOIN first_visit fv ON fv.patient_id = a.patient_id
    WHERE a.status = 'completada'
      AND a.date BETWEEN $1::date AND $2::date
      AND ($3::varchar IS NULL OR a.clinic_id = $3)
)
SELECT
    COUNT(*) FILTER (WHERE first_date BETWEEN $1::date AND $2::date) AS new_patients,
    COUNT(*) FILTER (WHERE first_date < $1::date) AS returning_patients,
    COUNT(*) AS total_patients
FROM period_patients
`

type GetNewVsReturningParams struct {
	DateFrom pgtype.Date `json:"date_from"`
	DateTo   pgtype.Date `json:"date_to"`
	ClinicID pgtype.Text `json:"clinic_id"`
}

type GetNewVsReturningRow struct {
	NewPatients       int64 `json:"new_patients"`
	ReturningPatients int64 `json:"returning_patients"`
	TotalPatients     int64 `json:"total_patients"`
}

// M3: Pacientes nuevas vs recurrentes en el período.
// Nueva = su primera cita completada en todo Nua cae dentro del rango.
func (q *Queries) GetNewVsReturning(ctx context.Context, arg GetNewVsReturningParams) (GetNewVsReturningRow, error) {
	row := q.db.QueryRow(ctx, getNewVsReturning, arg.DateFrom, arg.DateTo, arg.ClinicID)
	var i GetNewVsReturningRow
	err := row.Scan(&i.NewPatients, &i.ReturningPatients, &i.TotalPatients)
	return i, err
}

const getNewVsReturningByMonth = `-- name: GetNewVsReturningByMonth :many
WITH first_visit AS (
    SELECT patient_id, MIN(date) AS first_date
    FROM appointments
    WHERE status = 'completada'
    GROUP BY patient_id
)
SELECT
    to_char(a.date, 'YYYY-MM') AS month,
    COUNT(DISTINCT a.patient_id) FILTER (WHERE fv.first_date BETWEEN date_trunc('month', a.date)::date AND (date_trunc('month', a.date) + interval '1 month' - interval '1 day')::date) AS new_patients,
    COUNT(DISTINCT a.patient_id) FILTER (WHERE fv.first_date < date_trunc('month', a.date)::date) AS returning_patients
FROM appointments a
JOIN first_visit fv ON fv.patient_id = a.patient_id
WHERE a.status = 'completada'
  AND a.date BETWEEN $1::date AND $2::date
  AND ($3::varchar IS NULL OR a.clinic_id = $3)
GROUP BY month
ORDER BY month
`

type GetNewVsReturningByMonthParams struct {
	DateFrom pgtype.Date `json:"date_from"`
	DateTo   pgtype.Date `json:"date_to"`
	ClinicID pgtype.Text `json:"clinic_id"`
}

type GetNewVsReturningByMonthRow struct {
	Month             string `json:"month"`
	NewPatients       int64  `json:"new_patients"`
	ReturningPatients int64  `json:"returning_patients"`
}

// M3: Desglose mensual de nuevas vs recurrentes
func (q *Queries) GetNewVsReturningByMonth(ctx context.Context, arg GetNewVsReturningByMonthParams) ([]GetNewVsReturningByMonthRow, error) {
	rows, err := q.db.Query(ctx, getNewVsReturningByMonth, arg.DateFrom, arg.DateTo, arg.ClinicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNewVsReturningByMonthRow
	for rows.Next() {
		var i GetNewVsReturningByMonthRow
		if err := rows.Scan(&i.Month, &i.NewPatients, &i.ReturningPatients); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
