// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: m4_revenue.sql

package operationalsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRevenueByClinic = `-- name: GetRevenueByClinic :many
SELECT
    c.id AS clinic_id,
    c.name AS clinic_name,
    s.specialty::text AS service_specialty,
    SUM(p.amount)::bigint AS revenue
FROM payments p
JOIN appointments a ON a.id = p.appointment_id
JOIN clinics c ON c.id = a.clinic_id
JOIN services s ON s.id = a.service_id
WHERE p.payment_date BETWEEN $1::date AND $2::date
  AND p.status = 'completado'
  AND ($3::varchar IS NULL OR a.clinic_id = ANY(string_to_array($3::varchar, ',')))
  AND ($4::varchar IS NULL OR s.specialty::text = ANY(string_to_array($4::varchar, ',')))
GROUP BY c.id, c.name, s.specialty
ORDER BY c.name, s.specialty
`

type GetRevenueByClinicParams struct {
	DateFrom  pgtype.Date `json:"date_from"`
	DateTo    pgtype.Date `json:"date_to"`
	ClinicID  pgtype.Text `json:"clinic_id"`
	Specialty pgtype.Text `json:"specialty"`
}

type GetRevenueByClinicRow struct {
	ClinicID         string `json:"clinic_id"`
	ClinicName       string `json:"clinic_name"`
	ServiceSpecialty string `json:"service_specialty"`
	Revenue          int64  `json:"revenue"`
}

// M4: Ingresos por clínica, desglosados por especialidad del servicio.
// Filtra por fecha de pago, no fecha de cita.
func (q *Queries) GetRevenueByClinic(ctx context.Context, arg GetRevenueByClinicParams) ([]GetRevenueByClinicRow, error) {
	rows, err := q.db.Query(ctx, getRevenueByClinic,
		arg.DateFrom,
		arg.DateTo,
		arg.ClinicID,
		arg.Specialty,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRevenueByClinicRow
	for rows.Next() {
		var i GetRevenueByClinicRow
		if err := rows.Scan(
			&i.ClinicID,
			&i.ClinicName,
			&i.ServiceSpecialty,
			&i.Revenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRevenueSummary = `-- name: GetRevenueSummary :one
SELECT COALESCE(SUM(p.amount), 0)::bigint AS total_revenue
FROM payments p
JOIN appointments a ON a.id = p.appointment_id
JOIN services s ON s.id = a.service_id
WHERE p.payment_date BETWEEN $1::date AND $2::date
  AND p.status = 'completado'
  AND ($3::varchar IS NULL OR a.clinic_id = ANY(string_to_array($3::varchar, ',')))
  AND ($4::varchar IS NULL OR s.specialty::text = ANY(string_to_array($4::varchar, ',')))
`

type GetRevenueSummaryParams struct {
	DateFrom  pgtype.Date `json:"date_from"`
	DateTo    pgtype.Date `json:"date_to"`
	ClinicID  pgtype.Text `json:"clinic_id"`
	Specialty pgtype.Text `json:"specialty"`
}

// M4: Total de ingresos en el período
func (q *Queries) GetRevenueSummary(ctx context.Context, arg GetRevenueSummaryParams) (int64, error) {
	row := q.db.QueryRow(ctx, getRevenueSummary,
		arg.DateFrom,
		arg.DateTo,
		arg.ClinicID,
		arg.Specialty,
	)
	var total_revenue int64
	err := row.Scan(&total_revenue)
	return total_revenue, err
}
