// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: m5_top_doctors.sql

package operationalsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTopDoctors = `-- name: GetTopDoctors :many
SELECT
    d.id AS doctor_id,
    d.name AS doctor_name,
    d.specialty::text AS specialty,
    c.name AS clinic_name,
    COUNT(*)::bigint AS completed_appointments
FROM appointments a
JOIN doctors d ON d.id = a.doctor_id
JOIN clinics c ON c.id = d.clinic_id
WHERE a.status = 'completada'
  AND a.date BETWEEN $1::date AND $2::date
  AND ($3::varchar IS NULL OR a.clinic_id = ANY(string_to_array($3::varchar, ',')))
  AND ($4::varchar IS NULL OR d.specialty::text = ANY(string_to_array($4::varchar, ',')))
GROUP BY d.id, d.name, d.specialty, c.name
ORDER BY completed_appointments DESC
LIMIT 10
`

type GetTopDoctorsParams struct {
	DateFrom  pgtype.Date `json:"date_from"`
	DateTo    pgtype.Date `json:"date_to"`
	ClinicID  pgtype.Text `json:"clinic_id"`
	Specialty pgtype.Text `json:"specialty"`
}

type GetTopDoctorsRow struct {
	DoctorID              string `json:"doctor_id"`
	DoctorName            string `json:"doctor_name"`
	Specialty             string `json:"specialty"`
	ClinicName            string `json:"clinic_name"`
	CompletedAppointments int64  `json:"completed_appointments"`
}

// M5: Ranking de doctoras por volumen de citas completadas
func (q *Queries) GetTopDoctors(ctx context.Context, arg GetTopDoctorsParams) ([]GetTopDoctorsRow, error) {
	rows, err := q.db.Query(ctx, getTopDoctors,
		arg.DateFrom,
		arg.DateTo,
		arg.ClinicID,
		arg.Specialty,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopDoctorsRow
	for rows.Next() {
		var i GetTopDoctorsRow
		if err := rows.Scan(
			&i.DoctorID,
			&i.DoctorName,
			&i.Specialty,
			&i.ClinicName,
			&i.CompletedAppointments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
