// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: m6_cancellation_rate.sql

package operationalsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCancellationRateByPeriod = `-- name: GetCancellationRateByPeriod :many
SELECT
    CASE
        WHEN $1::text = 'day'   THEN to_char(a.date, 'YYYY-MM-DD')
        WHEN $1::text = 'week'  THEN to_char(date_trunc('week', a.date), 'YYYY-MM-DD')
        WHEN $1::text = 'month' THEN to_char(a.date, 'YYYY-MM')
    END AS period,
    COUNT(*)::bigint AS total,
    COUNT(*) FILTER (WHERE a.status IN ('cancelada', 'no_show'))::bigint AS lost,
    CASE
        WHEN COUNT(*) = 0 THEN 0::numeric
        ELSE ROUND(COUNT(*) FILTER (WHERE a.status IN ('cancelada', 'no_show'))::numeric / COUNT(*) * 100, 1)
    END AS lost_rate
FROM appointments a
JOIN doctors d ON d.id = a.doctor_id
WHERE a.date BETWEEN $2::date AND $3::date
  AND a.status != 'agendada'
  AND ($4::varchar IS NULL OR a.clinic_id = ANY(string_to_array($4::varchar, ',')))
  AND ($5::varchar IS NULL OR a.doctor_id = $5)
  AND ($6::specialty IS NULL OR d.specialty = $6)
GROUP BY period
ORDER BY period
`

type GetCancellationRateByPeriodParams struct {
	GroupBy   string        `json:"group_by"`
	DateFrom  pgtype.Date   `json:"date_from"`
	DateTo    pgtype.Date   `json:"date_to"`
	ClinicID  pgtype.Text   `json:"clinic_id"`
	DoctorID  pgtype.Text   `json:"doctor_id"`
	Specialty NullSpecialty `json:"specialty"`
}

type GetCancellationRateByPeriodRow struct {
	Period   interface{} `json:"period"`
	Total    int64       `json:"total"`
	Lost     int64       `json:"lost"`
	LostRate interface{} `json:"lost_rate"`
}

// M6: Tasa de cancelación/no-show por período (excluye agendadas del denominador)
func (q *Queries) GetCancellationRateByPeriod(ctx context.Context, arg GetCancellationRateByPeriodParams) ([]GetCancellationRateByPeriodRow, error) {
	rows, err := q.db.Query(ctx, getCancellationRateByPeriod,
		arg.GroupBy,
		arg.DateFrom,
		arg.DateTo,
		arg.ClinicID,
		arg.DoctorID,
		arg.Specialty,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCancellationRateByPeriodRow
	for rows.Next() {
		var i GetCancellationRateByPeriodRow
		if err := rows.Scan(
			&i.Period,
			&i.Total,
			&i.Lost,
			&i.LostRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCancellationRateSummary = `-- name: GetCancellationRateSummary :one
SELECT
    COUNT(*)::bigint AS total,
    COUNT(*) FILTER (WHERE a.status = 'cancelada')::bigint AS cancelled,
    COUNT(*) FILTER (WHERE a.status = 'no_show')::bigint AS no_show,
    CASE
        WHEN COUNT(*) = 0 THEN 0::numeric
        ELSE ROUND(COUNT(*) FILTER (WHERE a.status IN ('cancelada', 'no_show'))::numeric / COUNT(*) * 100, 1)
    END AS lost_rate
FROM appointments a
JOIN doctors d ON d.id = a.doctor_id
WHERE a.date BETWEEN $1::date AND $2::date
  AND a.status != 'agendada'
  AND ($3::varchar IS NULL OR a.clinic_id = ANY(string_to_array($3::varchar, ',')))
  AND ($4::varchar IS NULL OR a.doctor_id = $4)
  AND ($5::specialty IS NULL OR d.specialty = $5)
`

type GetCancellationRateSummaryParams struct {
	DateFrom  pgtype.Date   `json:"date_from"`
	DateTo    pgtype.Date   `json:"date_to"`
	ClinicID  pgtype.Text   `json:"clinic_id"`
	DoctorID  pgtype.Text   `json:"doctor_id"`
	Specialty NullSpecialty `json:"specialty"`
}

type GetCancellationRateSummaryRow struct {
	Total     int64       `json:"total"`
	Cancelled int64       `json:"cancelled"`
	NoShow    int64       `json:"no_show"`
	LostRate  interface{} `json:"lost_rate"`
}

// M6: Tasa global de cancelación/no-show en el período
func (q *Queries) GetCancellationRateSummary(ctx context.Context, arg GetCancellationRateSummaryParams) (GetCancellationRateSummaryRow, error) {
	row := q.db.QueryRow(ctx, getCancellationRateSummary,
		arg.DateFrom,
		arg.DateTo,
		arg.ClinicID,
		arg.DoctorID,
		arg.Specialty,
	)
	var i GetCancellationRateSummaryRow
	err := row.Scan(
		&i.Total,
		&i.Cancelled,
		&i.NoShow,
		&i.LostRate,
	)
	return i, err
}
