// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: m7_avg_ticket.sql

package operationalsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAvgTicket = `-- name: GetAvgTicket :one
SELECT
    COALESCE(ROUND(AVG(p.amount)::numeric, 0), 0)::bigint AS avg_ticket,
    COUNT(DISTINCT p.appointment_id)::bigint AS paid_appointments,
    COALESCE(SUM(p.amount), 0)::bigint AS total_revenue
FROM payments p
JOIN appointments a ON a.id = p.appointment_id
JOIN services s ON s.id = a.service_id
WHERE a.status = 'completada'
  AND p.status = 'completado'
  AND p.payment_date BETWEEN $1::date AND $2::date
  AND ($3::varchar IS NULL OR a.clinic_id = $3)
  AND ($4::specialty IS NULL OR s.specialty = $4)
`

type GetAvgTicketParams struct {
	DateFrom  pgtype.Date   `json:"date_from"`
	DateTo    pgtype.Date   `json:"date_to"`
	ClinicID  pgtype.Text   `json:"clinic_id"`
	Specialty NullSpecialty `json:"specialty"`
}

type GetAvgTicketRow struct {
	AvgTicket        int64 `json:"avg_ticket"`
	PaidAppointments int64 `json:"paid_appointments"`
	TotalRevenue     int64 `json:"total_revenue"`
}

// M7: Ticket promedio global (monto promedio por cita completada con pago confirmado)
func (q *Queries) GetAvgTicket(ctx context.Context, arg GetAvgTicketParams) (GetAvgTicketRow, error) {
	row := q.db.QueryRow(ctx, getAvgTicket,
		arg.DateFrom,
		arg.DateTo,
		arg.ClinicID,
		arg.Specialty,
	)
	var i GetAvgTicketRow
	err := row.Scan(&i.AvgTicket, &i.PaidAppointments, &i.TotalRevenue)
	return i, err
}

const getAvgTicketByClinic = `-- name: GetAvgTicketByClinic :many
SELECT
    c.id AS clinic_id,
    c.name AS clinic_name,
    COALESCE(ROUND(AVG(p.amount)::numeric, 0), 0)::bigint AS avg_ticket,
    COUNT(DISTINCT p.appointment_id)::bigint AS paid_appointments
FROM payments p
JOIN appointments a ON a.id = p.appointment_id
JOIN clinics c ON c.id = a.clinic_id
JOIN services s ON s.id = a.service_id
WHERE a.status = 'completada'
  AND p.status = 'completado'
  AND p.payment_date BETWEEN $1::date AND $2::date
  AND ($3::varchar IS NULL OR a.clinic_id = $3)
  AND ($4::specialty IS NULL OR s.specialty = $4)
GROUP BY c.id, c.name
ORDER BY avg_ticket DESC
`

type GetAvgTicketByClinicParams struct {
	DateFrom  pgtype.Date   `json:"date_from"`
	DateTo    pgtype.Date   `json:"date_to"`
	ClinicID  pgtype.Text   `json:"clinic_id"`
	Specialty NullSpecialty `json:"specialty"`
}

type GetAvgTicketByClinicRow struct {
	ClinicID         string `json:"clinic_id"`
	ClinicName       string `json:"clinic_name"`
	AvgTicket        int64  `json:"avg_ticket"`
	PaidAppointments int64  `json:"paid_appointments"`
}

// M7: Ticket promedio desglosado por clínica
func (q *Queries) GetAvgTicketByClinic(ctx context.Context, arg GetAvgTicketByClinicParams) ([]GetAvgTicketByClinicRow, error) {
	rows, err := q.db.Query(ctx, getAvgTicketByClinic,
		arg.DateFrom,
		arg.DateTo,
		arg.ClinicID,
		arg.Specialty,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAvgTicketByClinicRow
	for rows.Next() {
		var i GetAvgTicketByClinicRow
		if err := rows.Scan(
			&i.ClinicID,
			&i.ClinicName,
			&i.AvgTicket,
			&i.PaidAppointments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvgTicketBySpecialty = `-- name: GetAvgTicketBySpecialty :many
SELECT
    s.specialty::text AS specialty,
    COALESCE(ROUND(AVG(p.amount)::numeric, 0), 0)::bigint AS avg_ticket,
    COUNT(DISTINCT p.appointment_id)::bigint AS paid_appointments
FROM payments p
JOIN appointments a ON a.id = p.appointment_id
JOIN services s ON s.id = a.service_id
WHERE a.status = 'completada'
  AND p.status = 'completado'
  AND p.payment_date BETWEEN $1::date AND $2::date
  AND ($3::varchar IS NULL OR a.clinic_id = $3)
  AND ($4::specialty IS NULL OR s.specialty = $4)
GROUP BY s.specialty
ORDER BY avg_ticket DESC
`

type GetAvgTicketBySpecialtyParams struct {
	DateFrom  pgtype.Date   `json:"date_from"`
	DateTo    pgtype.Date   `json:"date_to"`
	ClinicID  pgtype.Text   `json:"clinic_id"`
	Specialty NullSpecialty `json:"specialty"`
}

type GetAvgTicketBySpecialtyRow struct {
	Specialty        string `json:"specialty"`
	AvgTicket        int64  `json:"avg_ticket"`
	PaidAppointments int64  `json:"paid_appointments"`
}

// M7: Ticket promedio desglosado por especialidad
func (q *Queries) GetAvgTicketBySpecialty(ctx context.Context, arg GetAvgTicketBySpecialtyParams) ([]GetAvgTicketBySpecialtyRow, error) {
	rows, err := q.db.Query(ctx, getAvgTicketBySpecialty,
		arg.DateFrom,
		arg.DateTo,
		arg.ClinicID,
		arg.Specialty,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAvgTicketBySpecialtyRow
	for rows.Next() {
		var i GetAvgTicketBySpecialtyRow
		if err := rows.Scan(&i.Specialty, &i.AvgTicket, &i.PaidAppointments); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
