// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: m8_retention_cohorts.sql

package operationalsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCohortSizes = `-- name: GetCohortSizes :many
WITH first_visit AS (
    SELECT
        a.patient_id,
        date_trunc('month', MIN(a.date))::date AS cohort_month
    FROM appointments a
    WHERE a.status = 'completada'
      AND ($3::varchar IS NULL OR a.clinic_id = ANY(string_to_array($3::varchar, ',')))
    GROUP BY a.patient_id
)
SELECT
    to_char(cohort_month, 'YYYY-MM') AS cohort,
    COUNT(*)::bigint AS cohort_size
FROM first_visit
WHERE to_char(cohort_month, 'YYYY-MM') >= to_char($1::date, 'YYYY-MM')
  AND to_char(cohort_month, 'YYYY-MM') <= to_char($2::date, 'YYYY-MM')
GROUP BY cohort_month
ORDER BY cohort_month
`

type GetCohortSizesParams struct {
	DateFrom pgtype.Date `json:"date_from"`
	DateTo   pgtype.Date `json:"date_to"`
	ClinicID pgtype.Text `json:"clinic_id"`
}

type GetCohortSizesRow struct {
	Cohort     string `json:"cohort"`
	CohortSize int64  `json:"cohort_size"`
}

// M8: Tamaño de cada cohorte (pacientes con primera cita en ese mes)
func (q *Queries) GetCohortSizes(ctx context.Context, arg GetCohortSizesParams) ([]GetCohortSizesRow, error) {
	rows, err := q.db.Query(ctx, getCohortSizes, arg.DateFrom, arg.DateTo, arg.ClinicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCohortSizesRow
	for rows.Next() {
		var i GetCohortSizesRow
		if err := rows.Scan(&i.Cohort, &i.CohortSize); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRetentionCohorts = `-- name: GetRetentionCohorts :many
WITH first_visit AS (
    SELECT
        a.patient_id,
        date_trunc('month', MIN(a.date))::date AS cohort_month
    FROM appointments a
    WHERE a.status = 'completada'
      AND ($3::varchar IS NULL OR a.clinic_id = ANY(string_to_array($3::varchar, ',')))
    GROUP BY a.patient_id
),
cohort_activity AS (
    SELECT DISTINCT
        fv.cohort_month,
        fv.patient_id,
        date_trunc('month', a.date)::date AS activity_month
    FROM first_visit fv
    JOIN appointments a ON a.patient_id = fv.patient_id
    WHERE a.status = 'completada'
      AND ($3::varchar IS NULL OR a.clinic_id = ANY(string_to_array($3::varchar, ',')))
)
SELECT
    to_char(ca.cohort_month, 'YYYY-MM') AS cohort,
    (EXTRACT(YEAR FROM age(ca.activity_month, ca.cohort_month)) * 12
      + EXTRACT(MONTH FROM age(ca.activity_month, ca.cohort_month)))::integer AS month_offset,
    COUNT(DISTINCT ca.patient_id)::bigint AS active_patients
FROM cohort_activity ca
WHERE to_char(ca.cohort_month, 'YYYY-MM') >= to_char($1::date, 'YYYY-MM')
  AND to_char(ca.cohort_month, 'YYYY-MM') <= to_char($2::date, 'YYYY-MM')
GROUP BY ca.cohort_month, month_offset
ORDER BY ca.cohort_month, month_offset
`

type GetRetentionCohortsParams struct {
	DateFrom pgtype.Date `json:"date_from"`
	DateTo   pgtype.Date `json:"date_to"`
	ClinicID pgtype.Text `json:"clinic_id"`
}

type GetRetentionCohortsRow struct {
	Cohort         string `json:"cohort"`
	MonthOffset    int32  `json:"month_offset"`
	ActivePatients int64  `json:"active_patients"`
}

// M8: Cohortes de retención. Cada cohorte = mes de primera cita completada.
// Mide cuántos pacientes regresaron en meses +0, +1, +2, etc.
func (q *Queries) GetRetentionCohorts(ctx context.Context, arg GetRetentionCohortsParams) ([]GetRetentionCohortsRow, error) {
	rows, err := q.db.Query(ctx, getRetentionCohorts, arg.DateFrom, arg.DateTo, arg.ClinicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRetentionCohortsRow
	for rows.Next() {
		var i GetRetentionCohortsRow
		if err := rows.Scan(&i.Cohort, &i.MonthOffset, &i.ActivePatients); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
