// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package operationalsqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AppointmentStatus string

const (
	AppointmentStatusCompletada AppointmentStatus = "completada"
	AppointmentStatusCancelada  AppointmentStatus = "cancelada"
	AppointmentStatusNoShow     AppointmentStatus = "no_show"
	AppointmentStatusAgendada   AppointmentStatus = "agendada"
)

func (e *AppointmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppointmentStatus(s)
	case string:
		*e = AppointmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AppointmentStatus: %T", src)
	}
	return nil
}

type NullAppointmentStatus struct {
	AppointmentStatus AppointmentStatus `json:"appointment_status"`
	Valid             bool              `json:"valid"` // Valid is true if AppointmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppointmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AppointmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppointmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppointmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppointmentStatus), nil
}

type PaymentMethod string

const (
	PaymentMethodTC       PaymentMethod = "TC"
	PaymentMethodTD       PaymentMethod = "TD"
	PaymentMethodEfectivo PaymentMethod = "Efectivo"
)

func (e *PaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethod(s)
	case string:
		*e = PaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethod: %T", src)
	}
	return nil
}

type NullPaymentMethod struct {
	PaymentMethod PaymentMethod `json:"payment_method"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethod), nil
}

type PaymentStatus string

const (
	PaymentStatusCompletado  PaymentStatus = "completado"
	PaymentStatusPendiente   PaymentStatus = "pendiente"
	PaymentStatusReembolsado PaymentStatus = "reembolsado"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus `json:"payment_status"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type Specialty string

const (
	SpecialtyGinecologia Specialty = "ginecologia"
	SpecialtyObstetricia Specialty = "obstetricia"
	SpecialtyMenopausia  Specialty = "menopausia"
)

func (e *Specialty) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Specialty(s)
	case string:
		*e = Specialty(s)
	default:
		return fmt.Errorf("unsupported scan type for Specialty: %T", src)
	}
	return nil
}

type NullSpecialty struct {
	Specialty Specialty `json:"specialty"`
	Valid     bool      `json:"valid"` // Valid is true if Specialty is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSpecialty) Scan(value interface{}) error {
	if value == nil {
		ns.Specialty, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Specialty.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSpecialty) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Specialty), nil
}

type Appointment struct {
	ID        string            `json:"id"`
	PatientID string            `json:"patient_id"`
	DoctorID  string            `json:"doctor_id"`
	ClinicID  string            `json:"clinic_id"`
	ServiceID string            `json:"service_id"`
	Date      pgtype.Date       `json:"date"`
	Hour      pgtype.Time       `json:"hour"`
	Status    AppointmentStatus `json:"status"`
}

type Clinic struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Active      bool   `json:"active"`
	SlotsPerDay int32  `json:"slots_per_day"`
}

type Doctor struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Specialty Specialty `json:"specialty"`
	ClinicID  string    `json:"clinic_id"`
	Active    bool      `json:"active"`
}

type Patient struct {
	ID        string      `json:"id"`
	BirthDate pgtype.Date `json:"birth_date"`
}

type Payment struct {
	ID            string        `json:"id"`
	AppointmentID string        `json:"appointment_id"`
	Amount        int32         `json:"amount"`
	Method        PaymentMethod `json:"method"`
	Status        PaymentStatus `json:"status"`
	PaymentDate   pgtype.Date   `json:"payment_date"`
}

type Service struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Specialty Specialty `json:"specialty"`
	Price     int32     `json:"price"`
	Active    bool      `json:"active"`
}
