// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: placeholder.sql

package operationalsqlc

import (
	"context"
)

const placeholder = `-- name: Placeholder :one
SELECT 1 AS ok
`

// Query temporal mientras se define el schema operativo con el CSV
func (q *Queries) Placeholder(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, placeholder)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
