// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package operationalsqlc

import (
	"context"
)

type Querier interface {
	// Query temporal mientras se define el schema operativo con el CSV
	Placeholder(ctx context.Context) (int32, error)
}

var _ Querier = (*Queries)(nil)
