// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package operationalsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// M1: Citas agrupadas por período con desglose por estado.
	// Agrupa por día, semana o mes según el parámetro @group_by.
	GetAppointmentsByPeriod(ctx context.Context, arg GetAppointmentsByPeriodParams) ([]GetAppointmentsByPeriodRow, error)
	// M1: Totales de KPI para el período seleccionado
	GetAppointmentsSummary(ctx context.Context, arg GetAppointmentsSummaryParams) (GetAppointmentsSummaryRow, error)
	// M7: Ticket promedio global (monto promedio por cita completada con pago confirmado)
	GetAvgTicket(ctx context.Context, arg GetAvgTicketParams) (GetAvgTicketRow, error)
	// M7: Ticket promedio desglosado por clínica
	GetAvgTicketByClinic(ctx context.Context, arg GetAvgTicketByClinicParams) ([]GetAvgTicketByClinicRow, error)
	// M7: Ticket promedio desglosado por especialidad
	GetAvgTicketBySpecialty(ctx context.Context, arg GetAvgTicketBySpecialtyParams) ([]GetAvgTicketBySpecialtyRow, error)
	// M6: Tasa de cancelación/no-show por período (excluye agendadas del denominador)
	GetCancellationRateByPeriod(ctx context.Context, arg GetCancellationRateByPeriodParams) ([]GetCancellationRateByPeriodRow, error)
	// M6: Tasa global de cancelación/no-show en el período
	GetCancellationRateSummary(ctx context.Context, arg GetCancellationRateSummaryParams) (GetCancellationRateSummaryRow, error)
	// M8: Tamaño de cada cohorte (pacientes con primera cita en ese mes)
	GetCohortSizes(ctx context.Context, arg GetCohortSizesParams) ([]GetCohortSizesRow, error)
	// Rango de fechas con datos en citas
	GetDateRange(ctx context.Context) (GetDateRangeRow, error)
	// M3: Pacientes nuevas vs recurrentes en el período.
	// Nueva = su primera cita completada en todo Nua cae dentro del rango.
	GetNewVsReturning(ctx context.Context, arg GetNewVsReturningParams) (GetNewVsReturningRow, error)
	// M3: Desglose mensual de nuevas vs recurrentes
	GetNewVsReturningByMonth(ctx context.Context, arg GetNewVsReturningByMonthParams) ([]GetNewVsReturningByMonthRow, error)
	// M2: Ocupación por clínica. slots_per_day es la capacidad total de la clínica.
	GetOccupancyByClinic(ctx context.Context, arg GetOccupancyByClinicParams) ([]GetOccupancyByClinicRow, error)
	// M2: Ocupación por doctora. Cada doctora recibe slots_per_day / doctoras_activas de su clínica.
	GetOccupancyByDoctor(ctx context.Context, arg GetOccupancyByDoctorParams) ([]GetOccupancyByDoctorRow, error)
	// M8: Cohortes de retención. Cada cohorte = mes de primera cita completada.
	// Mide cuántos pacientes regresaron en meses +0, +1, +2, etc.
	GetRetentionCohorts(ctx context.Context, arg GetRetentionCohortsParams) ([]GetRetentionCohortsRow, error)
	// M4: Ingresos por clínica, desglosados por especialidad del servicio.
	// Filtra por fecha de pago, no fecha de cita.
	GetRevenueByClinic(ctx context.Context, arg GetRevenueByClinicParams) ([]GetRevenueByClinicRow, error)
	// M4: Total de ingresos en el período
	GetRevenueSummary(ctx context.Context, arg GetRevenueSummaryParams) (int64, error)
	// M5: Ranking de doctoras por volumen de citas completadas
	GetTopDoctors(ctx context.Context, arg GetTopDoctorsParams) ([]GetTopDoctorsRow, error)
	// Clínicas activas para el selector de filtros
	ListClinics(ctx context.Context) ([]ListClinicsRow, error)
	// Doctoras activas, opcionalmente filtradas por clínica
	ListDoctors(ctx context.Context, clinicID pgtype.Text) ([]ListDoctorsRow, error)
	// Especialidades disponibles en servicios
	ListSpecialties(ctx context.Context) ([]Specialty, error)
}

var _ Querier = (*Queries)(nil)
