// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package dashboardsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (name, key_hash)
VALUES ($1, $2)
RETURNING id, name, created_at
`

type CreateAPIKeyParams struct {
	Name    string `json:"name"`
	KeyHash string `json:"key_hash"`
}

type CreateAPIKeyRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Crea una nueva API key
func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, createAPIKey, arg.Name, arg.KeyHash)
	var i CreateAPIKeyRow
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const validateAPIKey = `-- name: ValidateAPIKey :one
UPDATE api_keys
SET last_used = now()
WHERE key_hash = $1 AND active = true
RETURNING id, name
`

type ValidateAPIKeyRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

// Busca una API key activa por su hash y actualiza last_used
func (q *Queries) ValidateAPIKey(ctx context.Context, keyHash string) (ValidateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, validateAPIKey, keyHash)
	var i ValidateAPIKeyRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
