// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package dashboardsqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (user_id, action, resource, details, ip_address)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAuditLogParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Action    AuditAction `json:"action"`
	Resource  pgtype.Text `json:"resource"`
	Details   []byte      `json:"details"`
	IpAddress *netip.Addr `json:"ip_address"`
}

// Registrar una acción en la bitácora
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.UserID,
		arg.Action,
		arg.Resource,
		arg.Details,
		arg.IpAddress,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT al.id, al.user_id, u.name as user_name, u.email as user_email,
       al.action, al.resource, al.details, al.ip_address, al.created_at
FROM audit_logs al
LEFT JOIN users u ON al.user_id = u.id
WHERE ($1::UUID IS NULL OR al.user_id = $1)
  AND ($2::TIMESTAMPTZ IS NULL OR al.created_at >= $2)
  AND ($3::TIMESTAMPTZ IS NULL OR al.created_at <= $3)
ORDER BY al.created_at DESC
LIMIT $5
OFFSET $4
`

type ListAuditLogsParams struct {
	UserID     pgtype.UUID        `json:"user_id"`
	StartDate  pgtype.Timestamptz `json:"start_date"`
	EndDate    pgtype.Timestamptz `json:"end_date"`
	PageOffset int32              `json:"page_offset"`
	PageSize   int32              `json:"page_size"`
}

type ListAuditLogsRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	UserName  pgtype.Text        `json:"user_name"`
	UserEmail pgtype.Text        `json:"user_email"`
	Action    AuditAction        `json:"action"`
	Resource  pgtype.Text        `json:"resource"`
	Details   []byte             `json:"details"`
	IpAddress *netip.Addr        `json:"ip_address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Listar bitácora con filtros opcionales de usuario y rango de fechas
func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogsRow
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserName,
			&i.UserEmail,
			&i.Action,
			&i.Resource,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
