// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dashboardsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Asignar una clínica a un usuario
	AssignClinicToUser(ctx context.Context, arg AssignClinicToUserParams) error
	// Registrar una acción en la bitácora
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	// Almacenar un nuevo refresh token
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	// Crear nuevo usuario (solo admin puede ejecutar esta acción)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	// Desactivar usuario (soft delete)
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	// Obtener las clínicas asignadas a un usuario (para clinic_director)
	GetClinicIDsByUserID(ctx context.Context, userID pgtype.UUID) ([]int32, error)
	// Buscar refresh token por hash para validación
	GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	// Buscar usuario por email para el login
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Obtener usuario por ID para el endpoint /auth/me
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	// Listar bitácora con filtros opcionales de usuario y rango de fechas
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error)
	// Listar todos los usuarios para gestión administrativa
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	// Remover todas las clínicas asignadas a un usuario (para reasignación)
	RemoveClinicsFromUser(ctx context.Context, userID pgtype.UUID) error
	// Revocar todos los refresh tokens de un usuario (cambio de password, seguridad)
	RevokeAllUserTokens(ctx context.Context, userID pgtype.UUID) error
	// Revocar un refresh token específico (logout)
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	// Actualizar datos de un usuario
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
}

var _ Querier = (*Queries)(nil)
