// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_clinics.sql

package dashboardsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignClinicToUser = `-- name: AssignClinicToUser :exec
INSERT INTO user_clinics (user_id, clinic_id)
VALUES ($1, $2)
ON CONFLICT (user_id, clinic_id) DO NOTHING
`

type AssignClinicToUserParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	ClinicID int32       `json:"clinic_id"`
}

// Asignar una clínica a un usuario
func (q *Queries) AssignClinicToUser(ctx context.Context, arg AssignClinicToUserParams) error {
	_, err := q.db.Exec(ctx, assignClinicToUser, arg.UserID, arg.ClinicID)
	return err
}

const getClinicIDsByUserID = `-- name: GetClinicIDsByUserID :many
SELECT clinic_id
FROM user_clinics
WHERE user_id = $1
`

// Obtener las clínicas asignadas a un usuario (para clinic_director)
func (q *Queries) GetClinicIDsByUserID(ctx context.Context, userID pgtype.UUID) ([]int32, error) {
	rows, err := q.db.Query(ctx, getClinicIDsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var clinic_id int32
		if err := rows.Scan(&clinic_id); err != nil {
			return nil, err
		}
		items = append(items, clinic_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeClinicsFromUser = `-- name: RemoveClinicsFromUser :exec
DELETE FROM user_clinics
WHERE user_id = $1
`

// Remover todas las clínicas asignadas a un usuario (para reasignación)
func (q *Queries) RemoveClinicsFromUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeClinicsFromUser, userID)
	return err
}
